steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', '$TAG_NAME','--max-instances', '3', '--memory', '1000Mi', '--image', 'asia.gcr.io/$PROJECT_ID/$TAG_NAME', '--region', 'us-west2', '--platform', 'managed', '--allow-unauthenticated', '--vpc-connector', 'hu-conn', '--add-cloudsql-instances', 'huex-post', '--set-env-vars', 'DBN=car-dealer']
logsBucket: 'gs://us-gcp-ame-con-116-npd-1_cloudbuild/$TAG_NAME'
